["CNBetaWin2.2.2"]
dispatch_seed = "370bad9b440b0157"
design_data_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_9520213_6bafe1eca9/client/"
design_data_revision = "9520213"
design_data_files = '[{"fileName": "data_version", "fileSize": 4722, "fileMD5": "10842184658586875354"}]'
game_res_url = "https://autopatchcn.juequling.com/game_res/beta_live/output_9520213_6bafe1eca9/client/"
game_res_branch = "beta_live"
game_audio_revision = "9515037"
game_res_revision = "9520213"
game_res_files = '[{"fileName": "res_version", "fileSize": 2341658, "fileMD5": "10341753372723753703"}, {"fileName": "audio_version", "fileSize": 30438, "fileMD5": "16542188190915034465"}, {"fileName": "base_revision", "fileSize": 18, "fileMD5": "17766880741347597652"}]'
silence_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_9520213_6bafe1eca9/client_silence/"
silence_revision = "9518430"
silence_files = '[{"fileName": "silence_version", "fileSize": 645, "fileMD5": "12045943431862209247"}]'
